[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.31.0"
ci = "github"
hosting = "github"
installers = ["shell", "powershell", "npm", "homebrew"]
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "aarch64-unknown-linux-musl", "x86_64-unknown-linux-musl", "aarch64-pc-windows-msvc", "x86_64-pc-windows-msvc"]
install-path = "CARGO_HOME"
install-updater = false
npm-scope = "@happytoolin"
tap = "happytoolin/homebrew-happytap"
formula = "hni"
bin-aliases = { hni = ["ni", "nr", "nlx", "nru", "nun", "nci", "na", "np", "ns"] }
publish-jobs = ["npm", "homebrew"]
